exports.SCENES = {
  REGISTRATION: 'REGISTRATION',
  VIEW_BOOKING: 'VIEW_BOOKING',
  BOOKING: 'BOOKING',
  CREATE_SEAT: 'CREATE_SEAT',
};

export const ADMIN_IDS = ['avazhov'];

export enum SCENES {
  REGISTRATION = 'REGISTRATION',
  VIEW_BOOKING = 'VIEW_BOOKING',
  BOOKING = 'BOOKING',
  CREATE_SEAT = 'CREATE_SEAT',
}
